# Generated by Django 5.0.1 on 2024-01-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt_backend', '0005_rename_lat_treasure_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasure',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='treasure',
            old_name='longitude',
            new_name='lng',
        ),
    ]
