# Generated by Django 5.0.1 on 2024-01-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt_backend', '0008_treasure_collected_by_profiletreasure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileTreasure',
            new_name='CollectedTreasure',
        ),
    ]
