# Generated by Django 5.0.1 on 2024-01-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt_backend', '0009_rename_profiletreasure_collectedtreasure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectedTreasure',
        ),
    ]
