# Generated by Django 5.0.1 on 2024-01-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt_backend', '0014_alter_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='default_avatar.png', max_length=255),
        ),
    ]
