# Generated by Django 5.0.1 on 2024-01-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt_backend', '0015_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='treasure_hunt_backend.profile'),
        ),
    ]
